### ISSUE TITLE
Wiki Data Formation Problem, Need Sentence Split

### ISSUE THREAD

**Issue by zheolong** [attardi/wikiextractor#162]
I'm checking and converting the wiki data for BERT pre-trainning, just like below:

![11_06_17__01_09_2019](https://user-images.githubusercontent.com/5104916/50875007-5f6ccf00-1401-11e9-9eda-5e7e81ac339c.jpg)

When the process finished, I've got 12792 files, one of these files shows like below:

<img width="1412" alt="2019-01-09 10 58 38" src="https://user-images.githubusercontent.com/5104916/50875004-5aa81b00-1401-11e9-8e5f-3d033ed2643c.png">

One line means represents one paragraph, but what we need is one line for one sentence, so am I wrong, or the script is not complete ? Do you have the complete script to do the whole job ?

**Comment by netw0rkf10w** [comment]
Hi @zheolong. Could you share with me how you resolved this? Thank you very much in advance!

**Comment by Bachstelze** [comment]
I don't think that the issue is really solved. BERT doesn't necessarily need single sentences: https://github.com/google-research/bert/issues/341
WikiMatrix used [syntok](https://github.com/fnl/syntok) for some sentence segmentations. Have a look a the [syntok blog post]( http://fnl.es/segtok-a-segmentation-and-tokenization-library.html ) for more details.
