### ISSUE TITLE
Missing file WikiExtractor.py

### ISSUE THREAD

**Issue by ameyagodbole** [attardi/wikiextractor#212]
The file was deleted in one of the recent commits.

**Comment by dnishiyama** [comment]
Looks like it's in "b13d447 - (8 hours ago) Removed scripts directory. - attardi" but not "6675c69 - (4 hours ago) Created PyPi release. - attardi"
There were some major changes to the repository, and I figured that the structure had changed so that WikiExtractor.py wasn't needed. But I haven't been able to get  it to work with the new instructions yet. Anyone else having success?

**Comment by tgalery** [comment]
nope, which is a major bummer cause a lot of people use this

**Comment by rhn19** [comment]
Install it using pip & then run the module as a script using "python -m"

**Comment by cutejue** [comment]
I found a trick to get WikiExtractor.py that :1/ "pip install wikiextractor" and you will see you are able to "from wikiextractor.WikiExtractor import version", which indicating the WikiExtractor.py is existed in your pip list. 2/copy WE.py to whatever file. and uninstall wikiextractor. 3/gitclone or download the latest project (missing WE.py), and move the WE.py you have copied before to the we-master/wikiextractor.  It work!

**Comment by ilos-vigil** [comment]
> Install it using pip & then run the module as a script using "python -m"

FYI wikiextractor from `pip` is a bit outdated (updated last year)

**Comment by Oymate** [comment]
I don't have pip and I can't install it in docker.

**Comment by attardi** [comment]
Should be fixed now. Thank you.
