### ISSUE TITLE
 from .extract import Extractor, ignoreTag

### ISSUE THREAD

**Issue by nocoolsandwich** [attardi/wikiextractor#221]
`Traceback (most recent call last):
  File "WikiExtractor.py", line 62, in <module>
    from .extract import Extractor, ignoreTag
ImportError: attempted relative import with no known parent package
`

if i delect the dot
` from extract import Extractor, ignoreTag`

then
`NameError: name 'define_template' is not defined`

nobody meet this problem???

**Comment by SandeepRamesh** [comment]
i have the same problem

**Comment by nocoolsandwich** [comment]
i guess you can import it from python   
`import wikiextractor` 
and check   
`wikiextractor.__path__`  
then locate the path and continue.

**Comment by sugyeonge** [comment]
I had same problem, too.
'define_template' belongs to 'extract.py', so I add like this:
**from extract import Extractor, ignoreTag, define_template**

**Comment by hxzd5568** [comment]
I also tried with "from extract import Extractor, ignoreTag, define_template",but there is still problem 

> I had same problem, too.
> 'define_template' belongs to 'extract.py', so I add like this:
> **from extract import Extractor, ignoreTag, define_template**

I also tried with "from extract import Extractor, ignoreTag, define_template",but there was still problem because  variable "templates" in wikiExtract.py  was defined in define_template
Traceback (most recent call last):
  File "/wikiextractor/wikiextractor/WikiExtractor.py", line 609, in <module>
    main()
  File "//wikiextractor/wikiextractor/WikiExtractor.py", line 605, in main
    args.compress, args.processes)
  File "//wikiextractor/wikiextractor/WikiExtractor.py", line 321, in process_dump
    logging.info("Loaded %d templates in %.1fs", len(templates), template_load_elapsed)

**Comment by hxzd5568** [comment]
I have met the same problem and tied to solve by "from extract import Extractor, ignoreTag, define_template",but it doesn't work because other problem. I final solve the problem by followling https://github.com/attardi/wikiextractor/issues/222

**Comment by attardi** [comment]
Fixed, thank you.
